server:
  servlet:
    context-path: /enchanted
  port: 7878

spring:
  banner:
    # 自定义banner文件路径
    location: classpath:banner.txt

  redis:
    port: 6379
    host: 10.72.3.30
    password:

  datasource:
    url: jdbc:mysql://10.165.78.7:20303/kpmp_ultimate_xqy4?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: local_kpmp_mthk
    password: Ro9^8Vi$^H^u
#    url: jdbc:mysql://localhost:3306/enchanted
#    username: root
#    password: root


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual

    publisher-confirm-type: correlated
    publisher-returns: true


  main:
    allow-bean-definition-overriding: true
    banner-mode: off
